### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by maboroshin** [coffeerhyder/YouTube-alternative-Clients-and-Frontends-overview#2]
* VueTube has 1.7K commits and a development version available
* Hyperion https://github.com/zt64/Hyperion Now Nightly builds available.
* WebTube is now on Github (Fewer commits) : https://github.com/thewebtube/webtubeapp

**Comment by coffeerhyder** [comment]
So what I'm supposed to write/update in the readme now based on that info?

**Comment by maboroshin** [comment]
Your last update as of Apr 25, 2022. The first version 0.1 of VueTube was June 15, 2022.
In other words, "Work in progress" is considered an unavailable application category.
In other words, it may be appropriate to remove VueTube from the "Work in progress" list.

Similarly, another app that was only in the planning stages on discord is now on GitHub. You might rewrite from discord to Github. WebTube may be positioned the same as VueTube in the past, since executables are not yet available.

> Use a browser of your choice + open source adblocker like U Block Origin + SponsorBlock addon + Return YouTube Dislike addon + Return YouTube Dislike addon.

This duplicate of the Dislike addon may be a work in progress. You might want to delete one.

**Comment by coffeerhyder** [comment]
Done. Thanks for the update I've changed it accordingly.

**Comment by amanzrx4** [comment]
Hi @coffeerhyder @maboroshin I'd like to create my own youtube client with some addons like changing the themes & adding some AI features, I'm curious how do these clients work, they look exactly the same as youtube but with patches like adblocking. I'm guessing they've forked from a common project. Can you help me out understanding this better? Thankyou 🙌
